status = error
name = YMatrixProbeLogConfig

appender.console.type = Console
appender.console.name = CONSOLE
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss.SSS} %-5p %c{1}: %m%n

rootLogger.level = warn
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = CONSOLE

logger.spark.name = org.apache.spark
logger.spark.level = warn

logger.sparkui.name = org.apache.spark.ui
logger.sparkui.level = warn

logger.jetty.name = org.spark_project.jetty
logger.jetty.level = warn

logger.eclipsejetty.name = org.eclipse.jetty
logger.eclipsejetty.level = warn

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn

logger.parquet1.name = org.apache.parquet
logger.parquet1.level = error

logger.parquet2.name = parquet
logger.parquet2.level = error

logger.gp.name = com.itsumma.gpconnector
logger.gp.level = info

logger.gpwriter.name = com.itsumma.gpconnector.writer
logger.gpwriter.level = info

logger.gprmi.name = com.itsumma.gpconnector.rmi
logger.gprmi.level = info

logger.gpfdist.name = com.itsumma.gpconnector.gpfdist
logger.gpfdist.level = info
